surname =input("Введите фамилию:")
name = input("Введите имя:")
group = input("Введите группу:")
city = input("Введите город:")
age = int(input("Введите возраст в полных годах:"))
subject = input("Введите любимый предмет:")
hours = float(input("Введите количество часов:"))
print("            КАРТОЧКА СТУДЕНТА")
print(f"Фамилия:          {surname}")
print(f"Имя:              {name}")
print(f"Группа:           {group}")
print(f"Город:            {city}")
print(f"Возраст:          {age} лет")
print(f"Возраст через 4 года: {age + 4} лет")
print(f"Любимый предмет:  {subject}")
print(f"Часов в неделю:   {hours:.2f}")
print(f"За 4 недели:      {hours * 4:.2f} ч")
print(f"В день (среднее): {hours / 7:.2f} ч")
